"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "he";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const DICTIONARY: Record<Language, Record<string, string>> = {
  en: {
    "header.name": "Eran Ben Barak",
    "nav.fonts": "Fonts",
    "nav.designs": "Designs",
    "nav.toolbox": "Tool Box",
    "nav.about": "About",
    "hero.title": "An independent type and graphic designer. Specializing in custom typefaces, logotypes, and branding.",
    "footer.rights": "All rights reserved.",
    "designs.manofim.title": "MANOFIM 17",
    "designs.manofim.description": "Branding for an art and performance festival in Jerusalem. The brief of this year was 'extreme points' and is visualized by industrial sharp design. I created a custom tri-lingual typeface for the project.",
    "designs.sticky.title": "STICKY",
    "designs.sticky.description": "Started as a group project in school, Simon Memel, Lucrezia Noro and I explored the limitations of working with tape and imitating a sign painter. The monolinear nature of the tool, the limited angle, and the speed of writing were the considerations that affected the shapes of letters. After the project was over I was tasked to finalize the typeface for release at ECAL typefaces.",
    "designs.turing.title": "THE TURING DEFENSE",
    "designs.turing.description": "The Turing Defense is an editorial project about the clash between human intuition and machine logic, centered on the historic chess match between Garry Kasparov and IBM's Deep Blue. Produced during my studies at ECAL, the book features a custom typeface designed with an optical size axis.",
    "designs.script.title": "SCRIPT IN STONE",
    "designs.script.description": "Script In Stone is a research-based typographic project and a thesis developed during my Master’s studies at ECAL. It explores the evolution of Hebrew letter-forms through Jewish tombstones in Central Europe. By treating the tombstone as a canvas for artistic expression, the work investigates the connection between tradition, culture, and the craft of stone carving versus calligraphy, ultimately bridging historical research with contemporary typographic design.",
    "designs.collaborators": "Collaborators",
    "designs.category.branding": "Branding",
    "designs.category.visual_language": "Visual Language",
    "designs.category.typeface_design": "Typeface Design",
    "designs.category.editorial_design": "Editorial Design",
    "designs.category.writing": "Writing",
    "fonts.page_title": "Typefaces",
    "fonts.styles_count": "styles with matching italic",
    "fonts.styles_count_single": "style",
    "about.page_title": "About",
    "about.bio1": "Hi! I'm Eran, an independent type and graphic designer originally from Israel, now based in Italy.",
    "about.bio2": "After working as a graphic designer in Israel for several years, I moved to Switzerland to complete my Master's in Type Design at ECAL. Today, I work independently,I am creating custom typefaces for brands and cultural institutions, specializing in the localization of Latin typefaces to Hebrew script, collaborating with international type foundries to publish retail fonts, and of course providing graphic design services and branding solutions.",
    "about.what_i_do": "What I Do",
    "about.service1": "Custom typeface design for brands & cultural projects",
    "about.service2": "Hebrew localization & multi-script type design",
    "about.service3": "Logotype & lettering",
    "about.service4": "Graphic design & visual identity",
    "about.service5": "Type consultation",
    "about.education": "Education",
    "about.edu1": "Master in Type Design | ECAL, Lausanne, Switzerland",
    "about.edu2": "B.Des. in Visual Communication | Bezalel, Jerusalem, Israel",
    "about.contact": "Contact",
    "about.contact_text": "For custom type design, freelance inquiries, or collaborations:",
    "tag.sans-serif": "Sans-serif",
    "tag.serif": "Serif",
    "tag.display": "Display",
    "tag.text": "Text",
    "tag.classic": "Classic",
    "tag.monospace": "Monospace",
    "tag.wild": "Wild",
    "tag.latin": "Latin",
    "tag.hebrew": "Hebrew",
    "tag.latin_hebrew": "Latin + Hebrew",
    "tag.collaboration": "Collaboration",
    "tag.in-process": "In process",
    "tag.experimental": "Experimental",
    "tag.grotesque": "Grotesque",
    "tag.mathematical": "Mathematical",
    "tag.variable": "Variable",
    "specimen.styles": "Styles",
    "specimen.tester": "Interactive Tester & Showcase",
    "specimen.features": "OpenType Features",
    "specimen.charset": "Character Set",
    "specimen.about": "Specifications & About",
    "specimen.designer": "Designer",
    "specimen.year": "Year",
    "specimen.category": "Category",
    "specimen.script": "Script",
    "on": "On",
    "off": "Off",
    "weight.thin": "Thin",
    "weight.light": "Light",
    "weight.regular": "Regular",
    "weight.medium": "Medium",
    "weight.semibold": "Semibold",
    "weight.demibold": "Demibold",
    "weight.bold": "Bold",
    "weight.extrabold": "Extrabold",
    "weight.ultrabold": "Ultrabold",
    "weight.black": "Black",
    "purchase.title": "Licensing & Purchase",
    "purchase.tier_label": "License Tier",
    "purchase.solo_title": "Solo / Freelance",
    "purchase.solo_desc": "1–3 computers. Desktop + Static Web.",
    "purchase.studio_title": "Studio / Small Business",
    "purchase.studio_desc": "4–10 computers. Desktop + Web (50k) + 1 App.",
    "purchase.business_title": "Business / Pro",
    "purchase.business_desc": "11–25 computers. Desktop + Web (500k) + 5 Apps.",
    "purchase.select_styles": "Select Styles",
    "purchase.all_styles": "All Styles",
    "purchase.discount_note": "30% discount applied for 5+ styles",
    "purchase.full_family_discount_disclaimer": "25% discount for buying the complete family",
    "purchase.buy_now": "Buy Now",
    "purchase.full_family": "Complete Family",
    "purchase.total": "Total",
    "purchase.currency_toggle": "Currency",
    "purchase.license_link": "View License Terms",
    "nav.terms": "Terms of Service",
    "nav.privacy": "Privacy Policy",
    "nav.refunds": "Refund Policy",
    "twister.title": "Twister",
    "twister.text": "Text",
    "twister.font": "Font",
    "twister.style": "Style",
    "twister.array_density": "Array Density",
    "twister.h_stack": "H-Stack",
    "twister.v_stack": "V-Stack",
    "twister.distance": "Distance",
    "twister.intensity": "Intensity",
    "twister.rotation_speed": "Rotation Speed",
    "twister.offset_curve": "Offset Curve",
    "twister.color": "Color",
    "twister.background": "Background",
    "twister.export": "Export",
    "twister.save_video": "Save Video",
    "twister.rendering": "Rendering Loop...",
    "twister.booting": "Booting Sequence...",
    "toolbox.title": "Tool Box",
    "toolbox.description": "Various tools I made for myself that you are welcome to use.",
    "toolbox.spatial": "Spatial",
    "toolbox.twister_name": "Twister",
    "toolbox.twister_desc": "Typography mapped onto continuous undulating 3D ribbons",
    "toolbox.mosaic_name": "Mosaic",
    "toolbox.mosaic_desc": "Merge two images in a smooth animated tile mosaic",
    "toolbox.image": "Image",
    "mosaic.title": "Mosaic",
    "mosaic.source1": "Source 1 (Tiles)",
    "mosaic.source2": "Source 2 (Target)",
    "mosaic.speed": "Speed",
    "mosaic.offset": "offset",
    "mosaic.tile_size": "Tile Size",
    "mosaic.export": "Export",
    "mosaic.save_video": "Save Video",
    "mosaic.rendering": "Rendering Loop...",
    "specimen.neoklass_link": "NeoKlass is sold at Fontef. For trial version and purchasing ->",
    "specimen.sticky_link": "Sticky is sold at ECAL Typefaces. For trial version and purchasing ->",
    "specimen.wilson_link": "Wilson is sold at Type Department. For trial version and purchasing ->",
    "specimen.skolar_link": "Skolar Sans Hebrew is sold at Rosetta Type. For trial version and purchasing ->",
    "specimen.in_process": "In Process. Will be available in the near future.",
    "specimen.converter_note": "* Prices are approximate and may vary at checkout due to currency conversion."
  },
  he: {
    "header.name": "ערן בן ברק",
    "nav.fonts": "פונטים",
    "nav.designs": "עיצובים",
    "nav.toolbox": "ארגז כלים",
    "nav.about": "אודות",
    "hero.title": "מעצב גרפי ופונטים עצמאי. מתמחה בעיצוב פונטים לחברות, לוגוטייפים ומיתוג.",
    "footer.rights": "כל הזכויות שמורות.",
    "designs.manofim.title": "מנופים 17",
    "designs.manofim.description": "מיתוג לפסטיבל אמנות ומופע בירושלים. הבריף השנה היה 'נקודות קצה' וקיבל ביטוי חזותי בעיצוב תעשייתי וחד. יצרתי פונט ייעודי תלת-לשוני עבור הפרויקט.",
    "designs.sticky.title": "סטיקי",
    "designs.sticky.description": "הפרויקט החל כפרויקט קבוצתי בלימודים, בו סיימון ממל, לוקרציה נורו ואני חקרנו את המגבלות של עבודה עם נייר דבק (טייפ) וחיקוי של צייר שלטים. המונולינריות של הכלי, הזווית המוגבלת ומהירות הכתיבה היו השיקולים שהשפיעו על צורות האותיות. לאחר סיום הפרויקט המשכתי לפתח ולהשלים את הפונט להפצה ב-ECAL Typefaces.",
    "designs.turing.title": "הגנת טיורינג",
    "designs.turing.description": "הגנת טיורינג (The Turing Defense) הוא פרויקט אדיטוריאל על המפגש בין אינטואיציה אנושית ללוגיקה ממוחשבת, המתמקד במשחק השחמט ההיסטורי בין גארי קספרוב למחשב 'דיפ בלו' של IBM. הספר, שנוצר במהלך לימודיי ב-ECAL, מלווה בפונט בעיצוב אישי עם ציר גודל אופטי.",
    "designs.script.title": "כתב באבן",
    "designs.script.description": "הפרויקט 'Script In Stone' (כתב באבן) הוא מחקר טיפוגרפי ופרויקט תזה שפותחו במהלך לימודי התואר השני ב-ECAL. הוא בוחן את התפתחות צורת האות העברית דרך התבוננות במצבות יהודיות במרכז אירופה. על ידי התייחסות למצבה כקנבס לביטוי אמנותי, העבודה חוקרת את הקשר בין מסורת, תרבות, ומלאכת הגילוף באבן אל מול הקליגרפיה, ומגשרת בין מחקר היסטורי לעיצוב טיפוגרפי עכשווי.",
    "designs.collaborators": "בשיתוף עם",
    "designs.category.branding": "מיתוג",
    "designs.category.visual_language": "שפה חזותית",
    "designs.category.typeface_design": "עיצוב פונט",
    "designs.category.editorial_design": "עיצוב מערכתי",
    "designs.category.writing": "כתיבה",
    "fonts.page_title": "פונטים",
    "fonts.styles_count": "משקלים כולל איטליק תואם",
    "fonts.styles_count_single": "משקל אחד",
    "about.page_title": "אודות",
    "about.bio1": "היי! אני ערן, מעצב פונטים ומעצב גרפי עצמאי במקור מישראל, כיום מבוסס באיטליה.",
    "about.bio2": "לאחר שעבדתי כמעצב גרפי בישראל במשך מספר שנים, עברתי לשוויץ להשלים את התואר השני שלי בעיצוב פונטים ב-ECAL. כיום, אני עובד באופן עצמאי, יוצר פונטים מותאמים אישית למותגים ומוסדות תרבות, מתמחה בלוקליזציה של פונטים לטיניים לעברית, משתף פעולה עם בתי פונטים בינלאומיים להוצאת פונטים מסחריים, וכמובן מעניק שירותי עיצוב גרפי ופתרונות מיתוג.",
    "about.what_i_do": "מה אני עושה",
    "about.service1": "עיצוב פונטים בהתאמה אישית למותגים ופרויקטים תרבותיים",
    "about.service2": "לוקליזציה לעברית ועיצוב רב-לשוני",
    "about.service3": "לוגוטייפ ולטרינג",
    "about.service4": "עיצוב גרפי וזהות ויזואלית",
    "about.service5": "ייעוץ טיפוגרפי",
    "about.education": "השכלה",
    "about.edu1": "תואר שני בעיצוב פונטים | ECAL, לוזאן, שוויץ",
    "about.edu2": "תואר ראשון בתקשורת חזותית | בצלאל, ירושלים, ישראל",
    "about.contact": "צרו קשר",
    "about.contact_text": "לשאלות לגבי עיצוב פונטים, פרילאנס או שיתופי פעולה:",
    "tag.sans-serif": "סנס-סריף",
    "tag.serif": "סריף",
    "tag.display": "דיספליי",
    "tag.text": "טקסט",
    "tag.classic": "קלאסי",
    "tag.monospace": "מונוספייס",
    "tag.wild": "פרוע",
    "tag.latin": "לטינית",
    "tag.hebrew": "עברית",
    "tag.latin_hebrew": "לטינית + עברית",
    "tag.collaboration": "שיתוף פעולה",
    "tag.in-process": "בפיתוח",
    "tag.experimental": "אקספרימנטלי",
    "tag.grotesque": "גרוטסק",
    "tag.mathematical": "מתמטי",
    "tag.variable": "וריאבילי",
    "specimen.styles": "סגנונות",
    "specimen.tester": "טסטר אינטראקטיבי ותצוגה",
    "specimen.features": "תכונות אופנטייפ",
    "specimen.charset": "סט תווים",
    "specimen.about": "מפרט ואודות",
    "specimen.designer": "מעצב",
    "specimen.year": "שנה",
    "specimen.category": "קטגוריה",
    "specimen.script": "כתב",
    "on": "פעיל",
    "off": "כבוי",
    "weight.thin": "דק",
    "weight.light": "לייט",
    "weight.regular": "רגיל",
    "weight.medium": "מדיום",
    "weight.semibold": "חצי עבה",
    "weight.demibold": "דמי בולד",
    "weight.bold": "בולד",
    "weight.extrabold": "עבה מאוד",
    "weight.ultrabold": "אולטרה בולד",
    "weight.black": "בלאק",
    "weight.italic": "איטליק",
    "purchase.title": "רישיון ורכישה",
    "purchase.tier_label": "רמת רישיון",
    "purchase.solo_title": "סולו / פרילאנס",
    "purchase.solo_desc": "1–3 מחשבים. דסקטופ + ווב סטטי.",
    "purchase.studio_title": "סטודיו / עסק קטן",
    "purchase.studio_desc": "4–10 מחשבים. דסקטופ + ווב (50 אלף) + אפליקציה 1.",
    "purchase.business_title": "ביזנס / פרו",
    "purchase.business_desc": "11–25 מחשבים. דסקטופ + ווב (500 אלף) + 5 אפליקציות.",
    "purchase.select_styles": "בחירת משקלים",
    "purchase.all_styles": "כל המשקלים",
    "purchase.discount_note": "הנחה של 30% ברכישת 5 משקלים ומעלה",
    "purchase.full_family_discount_disclaimer": "25% הנחה ברכישת המשפחה המלאה",
    "purchase.buy_now": "רכישה",
    "purchase.full_family": "משפחה מלאה",
    "purchase.total": "סה״כ",
    "purchase.currency_toggle": "מטבע",
    "purchase.license_link": "תנאי הרישיון",
    "nav.terms": "תנאי שימוש",
    "nav.privacy": "מדיניות פרטיות",
    "nav.refunds": "מדיניות החזרים",
    "twister.title": "טוויסטר",
    "twister.text": "טקסט",
    "twister.font": "פונט",
    "twister.style": "סגנון",
    "twister.array_density": "צפיפות",
    "twister.h_stack": "אופקי",
    "twister.v_stack": "אנכי",
    "twister.distance": "מרחק",
    "twister.intensity": "עוצמה",
    "twister.rotation_speed": "מהירות סיבוב",
    "twister.color": "צבע",
    "twister.background": "רקע",
    "twister.export": "ייצוא",
    "twister.save_video": "שמור סרטון",
    "twister.rendering": "מרנדר לופ...",
    "twister.booting": "מאתחל מערכת...",
    "toolbox.title": "ארגז כלים",
    "toolbox.description": "כלים שונים שבניתי לעצמי שאתם מוזמנים להשתמש בהם.",
    "toolbox.spatial": "מרחבי",
    "toolbox.twister_name": "טוויסטר",
    "toolbox.twister_desc": "טיפוגרפיה המוטלת על גבי סרטי תלת-ממד מתמשכים ומתפתלים",
    "toolbox.mosaic_name": "מוזאיקה",
    "toolbox.mosaic_desc": "מיזוג שתי תמונות במוזאיקה מונפשת",
    "toolbox.image": "תמונה",
    "mosaic.title": "מוזאיקה",
    "mosaic.source1": "מקור 1 (אריחים)",
    "mosaic.source2": "מקור 2 (מטרה)",
    "mosaic.speed": "מהירות",
    "mosaic.offset": "אופסט",
    "mosaic.tile_size": "גודל אריח",
    "mosaic.export": "ייצוא",
    "mosaic.save_video": "שמור סרטון",
    "mosaic.rendering": "מרנדר לופ...",
    "specimen.neoklass_link": "NeoKlass נמכר דרך Fontef. לגרסת ניסיון ורכישה ->",
    "specimen.sticky_link": "Sticky נמכר דרך ECAL Typefaces. לגרסת ניסיון ורכישה ->",
    "specimen.wilson_link": "Wilson נמכר דרך Type Department. לגרסת ניסיון ורכישה ->",
    "specimen.skolar_link": "Skolar Sans Hebrew נמכר דרך Rosetta Type. לגרסת ניסיון ורכישה ->",
    "specimen.in_process": "בפיתוח. יהיה זמין לרכישה בקרוב.",
    "specimen.converter_note": "* המחירים מוערכים ועשויים להשתנות במעמד התשלום עקב המרת מטבע."
  }
};

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    const userLang = navigator.language || (navigator as any).userLanguage;
    if (userLang && userLang.toLowerCase().includes("he")) {
      setLangState("he");
      document.documentElement.lang = "he";
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    document.documentElement.lang = newLang;
  };

  const t = (key: string) => DICTIONARY[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
